### ISSUE TITLE
Extend clip content

### ISSUE THREAD

**Issue by agorilla** [agorilla/felixwiedemann#1]
From @FelixWiedemann

Können wir den Text auf Thumbnail und Text auf Playerseite irgendwie seperate anlgen, da ich auf beiden unterschiedliche Info anzeigen möchte wie in den Mockups. Es wäre auch super wenn nur der Filmtitel fett sein könnte und alles andere nicht fett.

- [x] Ist es möglich die ‘Produzentenzeile’ auf Playerseite in der selben Zeile wie Regisseur anzuzeigen ?
- [x] Ist es möglich im Thumbnail und auf der Playerseite nur den Filmtitel Fett zu haben, und nicht ‘/feature film’ fett, siehe zweiter Screenshot im Anhang. Außerdem wird hier nicht ‘montage, oder Trailer etc angezeigt, nur auf der Player seite. Wenn das mit dem Fett komplizierter wird können wir das auch erstmal weglassen.

Nochmal im Überblick:

Thumbnail:
```
FILMTITEL  / Type of project 
Regisseur
```

Playerseite: 
```
FILMTITEL  / Type of project - Type of Clip 
Regisseur  / Produzenten und Produktionsfirma
Starring

Awards und Festivals (evtl mehrere Zeilen, kursiv)
```

**Comment by agorilla** [comment]
@FelixWiedemann Ist angepasst.

Du kannst nun in den Clip .json ein neues Feld `type` benutzen, das nur im Player angezeigt wird.

```
  {
    "title": "CITY OF TINY LIGHTS",
    "additional": "/ Feature Film",
    "type": "- Trailer",
    ...
  }
```

Den Rest konnte ich ohne Änderung an der .json anpassen (bei Producer musst du ab sofort auch ein "/ ..." eingeben.

**Comment by FelixWiedemann** [comment]
Hi Simon, ist es möglich die Zeilen länger zu machen ? Im Moment kommt es früh zum Zeilenumbruch ? Siehe Anhang...
<img width="756" alt="screen shot 2018-07-16 at 16 33 46" src="https://user-images.githubusercontent.com/39480267/42761422-2407a302-8916-11e8-8c67-92e1189d0ab9.png">

**Comment by agorilla** [comment]
Behoben mit Commit 3482a0d

Bislang war die maximale Textlänge 50% vom Video, jetzt ist es 100% vom Video.
