### ISSUE TITLE
Maintenance Fehlermeldung im Terminal

### ISSUE THREAD

**Issue by FelixWiedemann** [agorilla/felixwiedemann#16]
Hi Simon, wollte gerade weiter am Content arbeiten und bekomme jetzt aber folgende Fehlermeldungen im Terminal, ein Problem mit unnerved files ?
<img width="551" alt="screen shot 2018-07-17 at 18 30 56" src="https://user-images.githubusercontent.com/39480267/42828372-23ad7306-89f1-11e8-9ca5-e5f4546606c5.png">
 (siehe Anhang)

**Comment by FelixWiedemann** [comment]
*unmerged files meinte ich :-)

**Comment by agorilla** [comment]
@FelixWiedemann 

Öffne mal Terminal und wechsle in dein Projektverzeichnis und gebe folgendes ein:
`find . -name '.DS_Store' -type f -delete`

Das Problem ist, dass diese Dateien nicht im zentralen Repository mehr existieren, bei dir aber schon. Ich habe sie mittlerweile so eingestellt, dass Git sie ignoriert aber du hast noch einen älteren Stand.

Kannst du danach mal probieren `git pull --rebase` und dann falls es immer noch Fehler gibt nochmal den Screenshot posten?

**Comment by FelixWiedemann** [comment]
Hi Simon,

Habe ausgeführt: find . -name '.DS_Store' -type f -delete

Dann git pull --rebase , dann kam folgende Meldung : 

<img width="575" alt="screen shot 2018-07-17 at 22 59 37" src="https://user-images.githubusercontent.com/39480267/42842224-4338e7cc-8a15-11e8-9fcf-f789f98a0852.png">
