### ISSUE TITLE
Bug in Safari 9.1.3

### ISSUE THREAD

**Issue by FelixWiedemann** [agorilla/felixwiedemann#19]
@agorilla Hi Simon, habe auf dem Mac von meiner Mutter einen Darstellungsbug gesehen. Fotos im Anhang. 
- Auf der Indexseite wird 'Felix Wiedemann' und 'Cinematographer' auf zwei Zeilen dargestellt. 
- Die Thumbnails werden riesengroß und nur eins per Zeile dargestellt
- weisser Leerraum über der Navigationsleiste
- Bei einem Video kommt 'Nicht unterstützte Betrachtungsumgebung'

Specs: OSX 10.9.5    SAFARI: 9.1.3

Ich nehme an dass es am veralteten Betriebssystem liegt. Werde mal ein Update machen. Wäre aber trotzdem super wenn bei Leuten mit älterem Betriebssystem dieser Bug verhindert werden könnte ? Siehst Du da eine einfache Lösung ?

![bildschirmfoto 2018-08-16 um 17 53 41](https://user-images.githubusercontent.com/39480267/44299176-7f381500-a2f1-11e8-979b-637f772e4e9c.png)
![bildschirmfoto 2018-08-16 um 17 53 47](https://user-images.githubusercontent.com/39480267/44299177-7f381500-a2f1-11e8-9c4d-c78f89f609d9.png)
![bildschirmfoto 2018-08-16 um 17 56 36](https://user-images.githubusercontent.com/39480267/44299178-7f381500-a2f1-11e8-903a-8f19d80cdd97.png)

**Comment by agorilla** [comment]
@FelixWiedemann Es liegt am nicht vorhandenen CSS Grid Support von Safari 9.1. CSS Grid wird seit Safari 10.1 unterstützt, der vor 1,5 Jahren erschien.

Fallback für alte Safaris kann man einbauen bei Grid, aber dazu müssen wir einiges umbauen. Ich schicke dir ein Angebot per Mail.

**Comment by agorilla** [comment]
Header grid fallback implemented in 29718250351e06c1051fb97756384ee782f30ce0

**Comment by agorilla** [comment]
Clip list grid fallback implemented in 753b0c4a724f4823d50a1ee622c92a46bbd05d24

**Comment by agorilla** [comment]
@FelixWiedemann Wir haben nun ein Grid Fallback für Startseite, Header und Clip Thumbnails eingebaut.
