### ISSUE TITLE
Remember scroll position in clip list

### ISSUE THREAD

**Issue by agorilla** [agorilla/felixwiedemann#8]
From @FelixWiedemann 

Wenn man von der Playerseite  wieder auf Film & TV geht ist es möglich dass man dann wieder auf derselben Scrollposition ist wie vorher, also nicht wieder von oben runterscrollen muss?

**Comment by agorilla** [comment]
@FelixWiedemann Ist nun eingebaut.

**Comment by FelixWiedemann** [comment]
Funktioniert auf 2018.felixwiedemann.com manchmal auf Safari aber auch manchmal nicht ?

**Comment by agorilla** [comment]
Bei mir im Safari (v11.0.3) funktioniert es immer lokal aber auch auf dem Webserver.

Welche Safari-Version hast du und kannst du die Schritte stichpunktarig beschreiben, die du durchführst.

Was ich eingebaut habe ist, dass man wen man vom Player wieder auf den aktiven Navigationspunkt klickt, in der gleichen Scrollposition vor dem Player-Aufruf bleibt. 

Bei Wechsel vom Player auf einen anderen Navigationspunkt springt man ganz nach oben. Das wäre das Verhalten, dass ich erwarten würde.

**Comment by FelixWiedemann** [comment]
Jetzt funktioniert es top, sorry ich weiss auch nicht warum es vorhin nicht geklappt hat...
